version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/deploy"
  schedule:
    interval: weekly
