//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosCore.Data.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NosCore.Data.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You accepted point share !.
        /// </summary>
        public static string ACCEPTED_SHARE {
            get {
                return ResourceManager.GetString("ACCEPTED_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with SessionId {0} has arrived..
        /// </summary>
        public static string ACCOUNT_ARRIVED {
            get {
                return ResourceManager.GetString("ACCOUNT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string ADMINISTRATOR {
            get {
                return ResourceManager.GetString("ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurer.
        /// </summary>
        public static string ADVENTURER {
            get {
                return ResourceManager.GetString("ADVENTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in blacklist!.
        /// </summary>
        public static string ALREADY_BLACKLISTED {
            get {
                return ResourceManager.GetString("ALREADY_BLACKLISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is in exchange!.
        /// </summary>
        public static string ALREADY_EXCHANGE {
            get {
                return ResourceManager.GetString("ALREADY_EXCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already friends!.
        /// </summary>
        public static string ALREADY_FRIEND {
            get {
                return ResourceManager.GetString("ALREADY_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in group!.
        /// </summary>
        public static string ALREADY_IN_GROUP {
            get {
                return ResourceManager.GetString("ALREADY_IN_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken!.
        /// </summary>
        public static string ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        public static string ARCHER {
            get {
                return ResourceManager.GetString("ARCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to bind with this item?.
        /// </summary>
        public static string ASK_BIND {
            get {
                return ResourceManager.GetString("ASK_BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        public static string ASK_TO_DELETE {
            get {
                return ResourceManager.GetString("ASK_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the required files are missing, try again when you have all the required files..
        /// </summary>
        public static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Error.
        /// </summary>
        public static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Auth.
        /// </summary>
        public static string AUTH_INCORRECT {
            get {
                return ResourceManager.GetString("AUTH_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated Error..
        /// </summary>
        public static string AUTHENTICATED_ERROR {
            get {
                return ResourceManager.GetString("AUTHENTICATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client : {1} authenticated successfully!.
        /// </summary>
        public static string AUTHENTICATED_SUCCESS {
            get {
                return ResourceManager.GetString("AUTHENTICATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad drop amount..
        /// </summary>
        public static string BAD_DROP_AMOUNT {
            get {
                return ResourceManager.GetString("BAD_DROP_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your character does not fulfil the requirements needed to wear this item..
        /// </summary>
        public static string BAD_EQUIPMENT {
            get {
                return ResourceManager.GetString("BAD_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your specialist does not match with the fairy element..
        /// </summary>
        public static string BAD_FAIRY {
            get {
                return ResourceManager.GetString("BAD_FAIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string BAD_PASSWORD {
            get {
                return ResourceManager.GetString("BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank account is full..
        /// </summary>
        public static string BANK_FULL {
            get {
                return ResourceManager.GetString("BANK_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character added to blacklist!.
        /// </summary>
        public static string BLACKLIST_ADDED {
            get {
                return ResourceManager.GetString("BLACKLIST_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Player has blocked you!.
        /// </summary>
        public static string BLACKLIST_BLOCKED {
            get {
                return ResourceManager.GetString("BLACKLIST_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought an item from {0} {1} {2}!.
        /// </summary>
        public static string BUY_ITEM_FROM {
            get {
                return ResourceManager.GetString("BUY_ITEM_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have purchased an item!.
        /// </summary>
        public static string BUY_ITEM_VALID {
            get {
                return ResourceManager.GetString("BUY_ITEM_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not trade not tradable items!.
        /// </summary>
        public static string CANNOT_TRADE_NOT_TRADABLE_ITEM {
            get {
                return ResourceManager.GetString("CANNOT_TRADE_NOT_TRADABLE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not block your friend!.
        /// </summary>
        public static string CANT_BLOCK_FRIEND {
            get {
                return ResourceManager.GetString("CANT_BLOCK_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not change to the same class..
        /// </summary>
        public static string CANT_CHANGE_SAME_CLASS {
            get {
                return ResourceManager.GetString("CANT_CHANGE_SAME_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not equip a destroyed SP!.
        /// </summary>
        public static string CANT_EQUIP_DESTROYED_SP {
            get {
                return ResourceManager.GetString("CANT_EQUIP_DESTROYED_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find this character!.
        /// </summary>
        public static string CANT_FIND_CHARACTER {
            get {
                return ResourceManager.GetString("CANT_FIND_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t move an item in the shop !.
        /// </summary>
        public static string CANT_MOVE_ITEM_IN_SHOP {
            get {
                return ResourceManager.GetString("CANT_MOVE_ITEM_IN_SHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use any items in the shop..
        /// </summary>
        public static string CANT_USE_ITEM_IN_SHOP {
            get {
                return ResourceManager.GetString("CANT_USE_ITEM_IN_SHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cards Parsed!.
        /// </summary>
        public static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string CHANNEL {
            get {
                return ResourceManager.GetString("CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel will exit in brief moments..
        /// </summary>
        public static string CHANNEL_WILL_EXIT {
            get {
                return ResourceManager.GetString("CHANNEL_WILL_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Not loaded.
        /// </summary>
        public static string CHARACTER_NOT_INIT {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Character is offline.
        /// </summary>
        public static string CHARACTER_OFFLINE {
            get {
                return ResourceManager.GetString("CHARACTER_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your class was changed succesfully!.
        /// </summary>
        public static string CLASS_CHANGED {
            get {
                return ResourceManager.GetString("CLASS_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected, SessionId: {0}.
        /// </summary>
        public static string CLIENT_ARRIVED {
            get {
                return ResourceManager.GetString("CLIENT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client connected. ClientId = {0}.
        /// </summary>
        public static string CLIENT_CONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client disconnected. ClientId = {0}.
        /// </summary>
        public static string CLIENT_DISCONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost..
        /// </summary>
        public static string CONNECTION_LOST {
            get {
                return ResourceManager.GetString("CONNECTION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet with Header {0} is corrupt or PacketDefinition is invalid. Content: {1}.
        /// </summary>
        public static string CORRUPT_PACKET {
            get {
                return ResourceManager.GetString("CORRUPT_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Keepalive on client {0}.
        /// </summary>
        public static string CORRUPTED_KEEPALIVE {
            get {
                return ResourceManager.GetString("CORRUPTED_KEEPALIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database has been initialized..
        /// </summary>
        public static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database may not be up to date. Please consider updating your database..
        /// </summary>
        public static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not send the invitation yet. Please try again in {0} seconds..
        /// </summary>
        public static string DELAY_GROUP_REQUEST {
            get {
                return ResourceManager.GetString("DELAY_GROUP_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing done!.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many items on this map! Try again later!.
        /// </summary>
        public static string DROP_MAP_FULL {
            get {
                return ResourceManager.GetString("DROP_MAP_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} effect has been activated !.
        /// </summary>
        public static string EFFECT_ACTIVATED {
            get {
                return ResourceManager.GetString("EFFECT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Error: {0}.
        /// </summary>
        public static string ENCODE_ERROR {
            get {
                return ResourceManager.GetString("ENCODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the directory of files to parse.
        /// </summary>
        public static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change of class dequip all your items please..
        /// </summary>
        public static string EQ_NOT_EMPTY {
            get {
                return ResourceManager.GetString("EQ_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character changed while changing map. Do not abuse Commands. {0}.
        /// </summary>
        public static string ERROR_CHANGE_MAP {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding error {0}.
        /// </summary>
        public static string ERROR_DECODING {
            get {
                return ResourceManager.GetString("ERROR_DECODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has been thrown : {0}.
        /// </summary>
        public static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange blocked.
        /// </summary>
        public static string EXCHANGE_BLOCKED {
            get {
                return ResourceManager.GetString("EXCHANGE_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused your exchange request..
        /// </summary>
        public static string EXCHANGE_REFUSED {
            get {
                return ResourceManager.GetString("EXCHANGE_REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced disconnection of the client {0}..
        /// </summary>
        public static string FORCED_DISCONNECTION {
            get {
                return ResourceManager.GetString("FORCED_DISCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] wants to be your friend! Do you accept the request?.
        /// </summary>
        public static string FRIEND_ADD {
            get {
                return ResourceManager.GetString("FRIEND_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request accepted!.
        /// </summary>
        public static string FRIEND_ADDED {
            get {
                return ResourceManager.GetString("FRIEND_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend deleted!.
        /// </summary>
        public static string FRIEND_DELETED {
            get {
                return ResourceManager.GetString("FRIEND_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend is offline!.
        /// </summary>
        public static string FRIEND_OFFLINE {
            get {
                return ResourceManager.GetString("FRIEND_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request rejected!.
        /// </summary>
        public static string FRIEND_REJECTED {
            get {
                return ResourceManager.GetString("FRIEND_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request blocked!.
        /// </summary>
        public static string FRIEND_REQUEST_BLOCKED {
            get {
                return ResourceManager.GetString("FRIEND_REQUEST_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend request could not be completed because the user is disconnected..
        /// </summary>
        public static string FRIEND_REQUEST_DISCONNECTED {
            get {
                return ResourceManager.GetString("FRIEND_REQUEST_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request sent!.
        /// </summary>
        public static string FRIEND_REQUEST_SENT {
            get {
                return ResourceManager.GetString("FRIEND_REQUEST_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Friendlist is full!.
        /// </summary>
        public static string FRIENDLIST_FULL {
            get {
                return ResourceManager.GetString("FRIENDLIST_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the group admin!.
        /// </summary>
        public static string GROUP_ADMIN {
            get {
                return ResourceManager.GetString("GROUP_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has blocked the group invitations!.
        /// </summary>
        public static string GROUP_BLOCKED {
            get {
                return ResourceManager.GetString("GROUP_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group disbanded.
        /// </summary>
        public static string GROUP_CLOSED {
            get {
                return ResourceManager.GetString("GROUP_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group is full!.
        /// </summary>
        public static string GROUP_FULL {
            get {
                return ResourceManager.GetString("GROUP_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent!.
        /// </summary>
        public static string GROUP_INVITE {
            get {
                return ResourceManager.GetString("GROUP_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left the party.
        /// </summary>
        public static string GROUP_LEFT {
            get {
                return ResourceManager.GetString("GROUP_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation has been declined!.
        /// </summary>
        public static string GROUP_REFUSED {
            get {
                return ResourceManager.GetString("GROUP_REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a request to share the point of return with the members of your group.
        /// </summary>
        public static string GROUP_SHARE_INFO {
            get {
                return ResourceManager.GetString("GROUP_SHARE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Group request type.
        /// </summary>
        public static string GROUPREQUESTTYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("GROUPREQUESTTYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found Handler implementation for Packet with Header {0}.
        /// </summary>
        public static string HANDLER_NOT_FOUND {
            get {
                return ResourceManager.GetString("HANDLER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t exchange with shop keepers..
        /// </summary>
        public static string HAS_SHOP_OPENED {
            get {
                return ResourceManager.GetString("HAS_SHOP_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hero level have changed.
        /// </summary>
        public static string HERO_LEVEL_CHANGED {
            get {
                return ResourceManager.GetString("HERO_LEVEL_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N ActDescs Parsed! Region: {1}.
        /// </summary>
        public static string I18N_ACTDESC_PARSED {
            get {
                return ResourceManager.GetString("I18N_ACTDESC_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N BCards Parsed! Region: {1}.
        /// </summary>
        public static string I18N_BCARD_PARSED {
            get {
                return ResourceManager.GetString("I18N_BCARD_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Cards Parsed! Region: {1}.
        /// </summary>
        public static string I18N_CARD_PARSED {
            get {
                return ResourceManager.GetString("I18N_CARD_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Items Parsed! Region: {1}.
        /// </summary>
        public static string I18N_ITEM_PARSED {
            get {
                return ResourceManager.GetString("I18N_ITEM_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N MapIdDatas Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MAPIDDATA_PARSED {
            get {
                return ResourceManager.GetString("I18N_MAPIDDATA_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N MapPointDatas Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MAPPOINTDATA_PARSED {
            get {
                return ResourceManager.GetString("I18N_MAPPOINTDATA_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N NpcMonsters Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MPCMONSTER_PARSED {
            get {
                return ResourceManager.GetString("I18N_MPCMONSTER_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N NpcMonsterTalk Parsed! Region: {1}.
        /// </summary>
        public static string I18N_NPCMONSTERTALK_PARSED {
            get {
                return ResourceManager.GetString("I18N_NPCMONSTERTALK_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Quests Parsed! Region: {1}.
        /// </summary>
        public static string I18N_QUEST_PARSED {
            get {
                return ResourceManager.GetString("I18N_QUEST_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Skills Parsed! Region: {1}.
        /// </summary>
        public static string I18N_SKILL_PARSED {
            get {
                return ResourceManager.GetString("I18N_SKILL_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Waiting for {0}..
        /// </summary>
        public static string IN_WAITING_FOR {
            get {
                return ResourceManager.GetString("IN_WAITING_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to exchange with you..
        /// </summary>
        public static string INCOMING_EXCHANGE {
            get {
                return ResourceManager.GetString("INCOMING_EXCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the NosMerchant medal, you can use the NosBazar at any time on all maps..
        /// </summary>
        public static string INFO_BAZAAR {
            get {
                return ResourceManager.GetString("INFO_BAZAAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Id!.
        /// </summary>
        public static string INVALID_ACCOUNT {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in your nickname!.
        /// </summary>
        public static string INVALID_CHARNAME {
            get {
                return ResourceManager.GetString("INVALID_CHARNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only exchange tradable items..
        /// </summary>
        public static string INVALID_EXCHANGE {
            get {
                return ResourceManager.GetString("INVALID_EXCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exchange list..
        /// </summary>
        public static string INVALID_EXCHANGE_LIST {
            get {
                return ResourceManager.GetString("INVALID_EXCHANGE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password!.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inventory is full.
        /// </summary>
        public static string INVENTORY_FULL {
            get {
                return ResourceManager.GetString("INVENTORY_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to set as a return point ?.
        /// </summary>
        public static string INVITED_GROUP_SHARE {
            get {
                return ResourceManager.GetString("INVITED_GROUP_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has invited you to a group! Do you accept?.
        /// </summary>
        public static string INVITED_YOU_GROUP {
            get {
                return ResourceManager.GetString("INVITED_YOU_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Invite type.
        /// </summary>
        public static string INVITETYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("INVITETYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired.
        /// </summary>
        public static string ITEM_ACQUIRED {
            get {
                return ResourceManager.GetString("ITEM_ACQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Land of the Dead object {0} has been acquired..
        /// </summary>
        public static string ITEM_ACQUIRED_LOD {
            get {
                return ResourceManager.GetString("ITEM_ACQUIRED_LOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not drop that item!.
        /// </summary>
        public static string ITEM_NOT_DROPPABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_DROPPABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not drop that item here!.
        /// </summary>
        public static string ITEM_NOT_DROPPABLE_HERE {
            get {
                return ResourceManager.GetString("ITEM_NOT_DROPPABLE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item can not be sold!.
        /// </summary>
        public static string ITEM_NOT_SOLDABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SOLDABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t trade some item.
        /// </summary>
        public static string ITEM_NOT_TRADABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_TRADABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is no longer valid..
        /// </summary>
        public static string ITEM_TIMEOUT {
            get {
                return ResourceManager.GetString("ITEM_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items Loaded!.
        /// </summary>
        public static string ITEMS_LOADED {
            get {
                return ResourceManager.GetString("ITEMS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items parsed!.
        /// </summary>
        public static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your job level has changed!.
        /// </summary>
        public static string JOB_LEVEL_CHANGED {
            get {
                return ResourceManager.GetString("JOB_LEVEL_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You joined the group.
        /// </summary>
        public static string JOINED_GROUP {
            get {
                return ResourceManager.GetString("JOINED_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing language.
        /// </summary>
        public static string LANGUAGE_MISSING {
            get {
                return ResourceManager.GetString("LANGUAGE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] left the party!.
        /// </summary>
        public static string LEAVE_GROUP {
            get {
                return ResourceManager.GetString("LEAVE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your level has changed!.
        /// </summary>
        public static string LEVEL_CHANGED {
            get {
                return ResourceManager.GetString("LEVEL_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add more item on the bazaar because the limit is exceeded..
        /// </summary>
        public static string LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("LIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Port {0}.
        /// </summary>
        public static string LISTENING_PORT {
            get {
                return ResourceManager.GetString("LISTENING_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading MapInstances....
        /// </summary>
        public static string LOADING_MAPINSTANCES {
            get {
                return ResourceManager.GetString("LOADING_MAPINSTANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SP requires more Job Level to use it..
        /// </summary>
        public static string LOW_JOB_LVL {
            get {
                return ResourceManager.GetString("LOW_JOB_LVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SP requires more Reputation to use it..
        /// </summary>
        public static string LOW_REP {
            get {
                return ResourceManager.GetString("LOW_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magician.
        /// </summary>
        public static string MAGICIAN {
            get {
                return ResourceManager.GetString("MAGICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map does not exist!.
        /// </summary>
        public static string MAP_DONT_EXIST {
            get {
                return ResourceManager.GetString("MAP_DONT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapMonsters Loaded!.
        /// </summary>
        public static string MAPMONSTERS_LOADED {
            get {
                return ResourceManager.GetString("MAPMONSTERS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapNpcs Loaded!.
        /// </summary>
        public static string MAPNPCS_LOADED {
            get {
                return ResourceManager.GetString("MAPNPCS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Maps Loaded!.
        /// </summary>
        public static string MAPS_LOADED {
            get {
                return ResourceManager.GetString("MAPS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Map Parsed!.
        /// </summary>
        public static string MAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapTypes Parsed!.
        /// </summary>
        public static string MAPTYPES_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Artist.
        /// </summary>
        public static string MARTIALARTIST {
            get {
                return ResourceManager.GetString("MARTIALARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping to master server.
        /// </summary>
        public static string MASTER_SERVER_PING {
            get {
                return ResourceManager.GetString("MASTER_SERVER_PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping to master server failed.
        /// </summary>
        public static string MASTER_SERVER_PING_FAILED {
            get {
                return ResourceManager.GetString("MASTER_SERVER_PING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Master Server! Trying again in {0} seconds....
        /// </summary>
        public static string MASTER_SERVER_RETRY {
            get {
                return ResourceManager.GetString("MASTER_SERVER_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of gold reached!.
        /// </summary>
        public static string MAX_GOLD {
            get {
                return ResourceManager.GetString("MAX_GOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapMonsters Parsed!.
        /// </summary>
        public static string MONSTERS_PARSED {
            get {
                return ResourceManager.GetString("MONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the new party leader!.
        /// </summary>
        public static string NEW_LEADER {
            get {
                return ResourceManager.GetString("NEW_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the NosMarchand medal..
        /// </summary>
        public static string NO_BAZAAR_MEDAL {
            get {
                return ResourceManager.GetString("NO_BAZAAR_MEDAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist!.
        /// </summary>
        public static string NO_ITEM {
            get {
                return ResourceManager.GetString("NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server need at least nosville MAP to work!.
        /// </summary>
        public static string NO_MAP {
            get {
                return ResourceManager.GetString("NO_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no specialist card equipped..
        /// </summary>
        public static string NO_SP {
            get {
                return ResourceManager.GetString("NO_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No special properties wearable.
        /// </summary>
        public static string NO_SPECIAL_PROPERTIES_WEARABLE {
            get {
                return ResourceManager.GetString("NO_SPECIAL_PROPERTIES_WEARABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an adventurer..
        /// </summary>
        public static string NOT_ADVENTURER {
            get {
                return ResourceManager.GetString("NOT_ADVENTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough gold..
        /// </summary>
        public static string NOT_ENOUGH_GOLD {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_GOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough money to purchase that item!.
        /// </summary>
        public static string NOT_ENOUGH_MONEY {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough place..
        /// </summary>
        public static string NOT_ENOUGH_PLACE {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough reputation to purchase that item!.
        /// </summary>
        public static string NOT_ENOUGH_REPUT {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_REPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is not on your blacklist!.
        /// </summary>
        public static string NOT_IN_BLACKLIST {
            get {
                return ResourceManager.GetString("NOT_IN_BLACKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not yours!.
        /// </summary>
        public static string NOT_YOUR_ITEM {
            get {
                return ResourceManager.GetString("NOT_YOUR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} NpcMonsters Loaded!.
        /// </summary>
        public static string NPCMONSTERS_LOADED {
            get {
                return ResourceManager.GetString("NPCMONSTERS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} NpcMonster Parsed!.
        /// </summary>
        public static string NPCMONSTERS_PARSED {
            get {
                return ResourceManager.GetString("NPCMONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapNpcs Parsed!.
        /// </summary>
        public static string NPCS_PARSED {
            get {
                return ResourceManager.GetString("NPCS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your item has been added on the bazaar !.
        /// </summary>
        public static string OBJECT_IN_BAZAAR {
            get {
                return ResourceManager.GetString("OBJECT_IN_BAZAAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet received without character being set {0}.
        /// </summary>
        public static string PACKET_USED_WITHOUT_CHARACTER {
            get {
                return ResourceManager.GetString("PACKET_USED_WITHOUT_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Accounts?.
        /// </summary>
        public static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse ALL?.
        /// </summary>
        public static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Cards?.
        /// </summary>
        public static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Drops?.
        /// </summary>
        public static string PARSE_DROPS {
            get {
                return ResourceManager.GetString("PARSE_DROPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse I18N datas?.
        /// </summary>
        public static string PARSE_I18N {
            get {
                return ResourceManager.GetString("PARSE_I18N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Items?.
        /// </summary>
        public static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse MapNpcs?.
        /// </summary>
        public static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Maps?.
        /// </summary>
        public static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse MapTypes? we suggest using with MapTypeMaps.
        /// </summary>
        public static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse NpcMonsters?.
        /// </summary>
        public static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse NpcMonsterData?.
        /// </summary>
        public static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Npcs?.
        /// </summary>
        public static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Portals?.
        /// </summary>
        public static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Quests?.
        /// </summary>
        public static string PARSE_QUESTS {
            get {
                return ResourceManager.GetString("PARSE_QUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Recipes?.
        /// </summary>
        public static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shopitems?.
        /// </summary>
        public static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shops?.
        /// </summary>
        public static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shopskills?.
        /// </summary>
        public static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Skills?.
        /// </summary>
        public static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Teleporters?.
        /// </summary>
        public static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse TimeSpaces?.
        /// </summary>
        public static string PARSE_TIMESPACES {
            get {
                return ResourceManager.GetString("PARSE_TIMESPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform doesn&apos;t support console title..
        /// </summary>
        public static string PLATFORM_UNSUPORTED_CONSOLE_TITLE {
            get {
                return ResourceManager.GetString("PLATFORM_UNSUPORTED_CONSOLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} player is in store mode..
        /// </summary>
        public static string PLAYER_IN_SHOP {
            get {
                return ResourceManager.GetString("PLAYER_IN_SHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown PocketType.
        /// </summary>
        public static string POCKETTYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("POCKETTYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait before you teleport !.
        /// </summary>
        public static string PORTAL_DELAY {
            get {
                return ResourceManager.GetString("PORTAL_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Portal Parsed!.
        /// </summary>
        public static string PORTALS_PARSED {
            get {
                return ResourceManager.GetString("PORTALS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price limit is exceeded..
        /// </summary>
        public static string PRICE_EXCEEDED {
            get {
                return ResourceManager.GetString("PRICE_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Quests Parsed!.
        /// </summary>
        public static string QUESTS_PARSED {
            get {
                return ResourceManager.GetString("QUESTS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered on MasterServer.
        /// </summary>
        public static string REGISTRED_ON_MASTER {
            get {
                return ResourceManager.GetString("REGISTRED_ON_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sale is completed, you receive gold: {0}..
        /// </summary>
        public static string REMOVE_FROM_BAZAAR {
            get {
                return ResourceManager.GetString("REMOVE_FROM_BAZAAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To transform dismount the vehicle..
        /// </summary>
        public static string REMOVE_VEHICLE {
            get {
                return ResourceManager.GetString("REMOVE_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reputation has decreased!.
        /// </summary>
        public static string REPUT_DECREASED {
            get {
                return ResourceManager.GetString("REPUT_DECREASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reputation has changed!.
        /// </summary>
        public static string REPUTATION_CHANGED {
            get {
                return ResourceManager.GetString("REPUTATION_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RespawnTypes Parsed!.
        /// </summary>
        public static string RESPAWNTYPE_PARSED {
            get {
                return ResourceManager.GetString("RESPAWNTYPE_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all data!.
        /// </summary>
        public static string SAVING_ALL {
            get {
                return ResourceManager.GetString("SAVING_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your item {0} has been sold! {1}.
        /// </summary>
        public static string SELL_ITEM_VALIDE {
            get {
                return ResourceManager.GetString("SELL_ITEM_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent to user..
        /// </summary>
        public static string SEND_MESSAGE_TO_CHARACTER {
            get {
                return ResourceManager.GetString("SEND_MESSAGE_TO_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused to share the point of return with the group members.
        /// </summary>
        public static string SHARED_REFUSED {
            get {
                return ResourceManager.GetString("SHARED_REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not open an empty shop!.
        /// </summary>
        public static string SHOP_EMPTY {
            get {
                return ResourceManager.GetString("SHOP_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a shop away from the portal please..
        /// </summary>
        public static string SHOP_NEAR_PORTAL {
            get {
                return ResourceManager.GetString("SHOP_NEAR_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not open a shop in this map..
        /// </summary>
        public static string SHOP_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SHOP_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not open a shop in a raid..
        /// </summary>
        public static string SHOP_NOT_ALLOWED_IN_RAID {
            get {
                return ResourceManager.GetString("SHOP_NOT_ALLOWED_IN_RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only sell tradable items! Please, check the items you want to sell..
        /// </summary>
        public static string SHOP_ONLY_TRADABLE_ITEMS {
            get {
                return ResourceManager.GetString("SHOP_ONLY_TRADABLE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have opened a shop..
        /// </summary>
        public static string SHOP_OPEN {
            get {
                return ResourceManager.GetString("SHOP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to open the shop as you set it up?.
        /// </summary>
        public static string SHOP_PRIVATE_SHOP {
            get {
                return ResourceManager.GetString("SHOP_PRIVATE_SHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ShopItems Loaded!.
        /// </summary>
        public static string SHOPITEMS_LOADED {
            get {
                return ResourceManager.GetString("SHOPITEMS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ShopItems Parsed!.
        /// </summary>
        public static string SHOPITEMS_PARSED {
            get {
                return ResourceManager.GetString("SHOPITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shops Loaded!.
        /// </summary>
        public static string SHOPS_LOADED {
            get {
                return ResourceManager.GetString("SHOPS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shops Parsed!.
        /// </summary>
        public static string SHOPS_PARSED {
            get {
                return ResourceManager.GetString("SHOPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Skills Parsed!.
        /// </summary>
        public static string SKILLS_PARSED {
            get {
                return ResourceManager.GetString("SKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum quantity of Additional SPs!.
        /// </summary>
        public static string SP_ADDPOINTS_FULL {
            get {
                return ResourceManager.GetString("SP_ADDPOINTS_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are actually using an SP! Please untransform first..
        /// </summary>
        public static string SP_BLOCKED {
            get {
                return ResourceManager.GetString("SP_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SP is still at cooldown! Please wait {0}s.
        /// </summary>
        public static string SP_INLOADING {
            get {
                return ResourceManager.GetString("SP_INLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient SP points to transform!.
        /// </summary>
        public static string SP_NOPOINTS {
            get {
                return ResourceManager.GetString("SP_NOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP points increased by {0}!.
        /// </summary>
        public static string SP_POINTSADDED {
            get {
                return ResourceManager.GetString("SP_POINTSADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left of the secondary effects: {0} seconds.
        /// </summary>
        public static string STAY_TIME {
            get {
                return ResourceManager.GetString("STAY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Loaded!.
        /// </summary>
        public static string SUCCESSFULLY_LOADED {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string SURE_TO_DELETE {
            get {
                return ResourceManager.GetString("SURE_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swordman.
        /// </summary>
        public static string SWORDMAN {
            get {
                return ResourceManager.GetString("SWORDMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least &quot;Level 15&quot; and &quot;Job Level 20&quot; to change your class..
        /// </summary>
        public static string TOO_LOW_LEVEL {
            get {
                return ResourceManager.GetString("TOO_LOW_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seller does not have sufficient space to handle your money..
        /// </summary>
        public static string TOO_RICH_SELLER {
            get {
                return ResourceManager.GetString("TOO_RICH_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secondary effects have finished. {0}.
        /// </summary>
        public static string TRANSFORM_DISAPPEAR {
            get {
                return ResourceManager.GetString("TRANSFORM_DISAPPEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to request the group.
        /// </summary>
        public static string UNABLE_TO_REQUEST_GROUP {
            get {
                return ResourceManager.GetString("UNABLE_TO_REQUEST_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Equipment type: {0}.
        /// </summary>
        public static string UNKNOWN_EQUIPMENTTYPE {
            get {
                return ResourceManager.GetString("UNKNOWN_EQUIPMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown PicketType.
        /// </summary>
        public static string UNKNOWN_PICKERTYPE {
            get {
                return ResourceManager.GetString("UNKNOWN_PICKERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Reciever type.
        /// </summary>
        public static string UNKWNOWN_RECEIVERTYPE {
            get {
                return ResourceManager.GetString("UNKWNOWN_RECEIVERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gold has been updated successfully!.
        /// </summary>
        public static string UPDATE_GOLD {
            get {
                return ResourceManager.GetString("UPDATE_GOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SP card detected!.
        /// </summary>
        public static string USE_SP_WITHOUT_SP_ERROR {
            get {
                return ResourceManager.GetString("USE_SP_WITHOUT_SP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a friend!.
        /// </summary>
        public static string USER_IS_NOT_A_FRIEND {
            get {
                return ResourceManager.GetString("USER_IS_NOT_A_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not connected.
        /// </summary>
        public static string USER_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("USER_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player isn&apos;t in exchange..
        /// </summary>
        public static string USER_NOT_IN_EXCHANGE {
            get {
                return ResourceManager.GetString("USER_NOT_IN_EXCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualEntity does not exist: {0}.
        /// </summary>
        public static string VISUALENTITY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("VISUALENTITY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown VisualType: {0}.
        /// </summary>
        public static string VISUALTYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("VISUALTYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ask for an exchange with: {0}..
        /// </summary>
        public static string YOU_ASK_FOR_EXCHANGE {
            get {
                return ResourceManager.GetString("YOU_ASK_FOR_EXCHANGE", resourceCulture);
            }
        }
    }
}
