//  __  _  __    __   ___ __  ___ ___  
// |  \| |/__\ /' _/ / _//__\| _ \ __| 
// | | ' | \/ |`._`.| \_| \/ | v / _|  
// |_|\__|\__/ |___/ \__/\__/|_|_\___| 
// 
// Copyright (C) 2019 - NosCore
// 
// NosCore is a free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.ComponentModel.DataAnnotations;
using NosCore.Data.I18N;
using NosCore.Data.Dto;
using NosCore.Data.StaticEntities;
using NosCore.Data.DataAttributes;
using NosCore.Data.Enumerations.I18N;
using Mapster;

namespace NosCore.Data.Dto
{
	/// <summary>
	/// Represents a DTO class for NosCore.Database.Entities.ItemInstance.
	/// NOTE: This class is generated by GenerateDtos.tt
	/// </summary>
	public class ItemInstanceDto : IItemInstanceDto
	{
		public short Amount { get; set; }

	 	public System.Collections.Generic.ICollection<BazaarItemDto> BazaarItem { get; set; }

	 	public System.Collections.Generic.ICollection<MailDto> Mail { get; set; }

	 	public System.Collections.Generic.ICollection<WarehouseItemDto> WarehouseItems { get; set; }

	 	public CharacterDto BoundCharacter { get; set; }

	 	public long? BoundCharacterId { get; set; }

	 	public long CharacterId { get; set; }

	 	public short Design { get; set; }

	 	public int DurabilityPoint { get; set; }

	 	public ItemDto Item { get; set; }

	 	public System.DateTime? ItemDeleteTime { get; set; }

	 	public short ItemVNum { get; set; }

	 	public System.Collections.Generic.ICollection<InventoryItemInstanceDto> InventoryItemInstance { get; set; }

	 	public byte Upgrade { get; set; }

	 	public short Rare { get; set; }

	 	[Key]
		public System.Guid Id { get; set; }

	 }
}