<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    <ProjectReference Include="..\NosCore.Instances.Abstractions\NosCore.Instances.Abstractions.csproj" />
  </ItemGroup>
</Project>
