//  __  _  __    __   ___ __  ___ ___
// |  \| |/__\ /' _/ / _//__\| _ \ __|
// | | ' | \/ |`._`.| \_| \/ | v / _|
// |_|\__|\__/ |___/ \__/\__/|_|_\___|
//

namespace NosCore.Data.Enumerations.Buff
{
    public class BCardType
    {
        public enum CardType : byte
        {
            // 1-20
            SpecialAttack = 1,
            SpecialDefence = 2,
            AttackPower = 3,
            Target = 4,
            Critical = 5,
            SpecialCritical = 6,
            Element = 7,
            IncreaseDamage = 8,
            Defence = 9,
            DodgeAndDefencePercent = 10,
            Block = 11,
            Absorption = 12,
            ElementResistance = 13,
            EnemyElementResistance = 14,
            Damage = 15,
            GuarantedDodgeRangedAttack = 16,
            Morale = 17,
            Casting = 18,
            Move = 19,
            Reflection = 20,

            // 21-40
            DrainAndSteal = 21,
            HealingBurningAndCasting = 22,
            Hpmp = 23,
            SpecialisationBuffResistance = 24,
            Buff = 25,
            Summons = 26,
            SpecialEffects = 27,
            Capture = 28,
            SpecialDamageAndExplosions = 29,
            SpecialEffects2 = 30,
            CalculatingLevel = 31,
            Recovery = 32,
            MaxHpmp = 33,
            MultAttack = 34,
            MultDefence = 35,
            TimeCircleSkills = 36,
            RecoveryAndDamagePercent = 37,
            Count = 38,
            NoDefeatAndNoDamage = 39,
            SpecialActions = 40,

            // 41-60
            Mode = 41,
            NoCharacteristicValue = 42,
            LightAndShadow = 43,
            Item = 44,
            DebuffResistance = 45,
            SpecialBehaviour = 46,
            Quest = 47,
            SecondSpCard = 48,
            SpCardUpgrade = 49,
            HugeSnowman = 50,
            Drain = 51,
            BossMonstersSkill = 52,
            LordHatus = 53,
            LordCalvinas = 54,
            SeSpecialist = 55,
            FourthGlacernonFamilyRaid = 56,
            SummonedMonsterAttack = 57,
            BearSpirit = 58,
            SummonSkill = 59,
            InflictSkill = 60,

            // 61-80 Missingno = 61,
            HideBarrelSkill = 62,
            FocusEnemyAttentionSkill = 63,
            TauntSkill = 64,
            FireCannoneerRangeBuff = 65,
            VulcanoElementBuff = 66,
            DamageConvertingSkill = 67,
            MeditationSkill = 68,
            FalconSkill = 69,
            AbsorptionAndPowerSkill = 70,
            LeonaPassiveSkill = 71,
            FearSkill = 72,
            SniperAttack = 73,
            FrozenDebuff = 74,
            JumpBackPush = 75,
            FairyXpIncrease = 76,
            SummonAndRecoverHp = 77,
            TeamArenaBuff = 78,
            ArenaCamera = 79,
            DarkCloneSummon = 80,

            // 81-100
            AbsorbedSpirit = 81,
            AngerSkill = 82,
            MeteoriteTeleport = 83,
            StealBuff = 84,
            Type85 = 85,
            Type86 = 86,
            Type87 = 87,
            Type88 = 88,
            Type89 = 89,
            Type90 = 90,
            Type91 = 91,
            Type92 = 92,
            ElementPercentage = 93,
            ElementResistancePercentage = 94,
            Type95 = 95,
            Type96 = 96,
            Type97 = 97,
            Type98 = 98,
            Type99 = 99,
            Type100 = 100,

            //101 - ???
            Type101 = 101,
            Type102 = 102,
            Type103 = 103,
            Type104 = 104,
            Type107 = 107,
            Type108 = 108,
            Type109 = 109,
            Type110 = 110,

            Type114 = 114,
            ArmourPiercing = 118,
            HeatAndGravity = 120,
            FuelPoints = 122,
            TokenSystem = 124,
            Type105 = 105,
            Type106 = 106,
            MateSynergy = 111,
            MateAndSquad = 112,
            SquadAndGravity = 113,
            Fishing = 115,
            Type116 = 116,
            Type117 = 117,
            HeatPoints = 119,
            Type121 = 121,
            Type123 = 123,
            Type125 = 125,
            Type126 = 126,
            Type127 = 127,
            Type128 = 128,
            Type129 = 129,
            HeroSummonAndSync = 130,
            Type131 = 131,

            Spsl = 200
        }
    }
}
