ARG REPO=mcr.microsoft.com/dotnet/runtime
FROM $REPO:5.0-alpine

RUN apk add --no-cache icu-libs	# Install .NET
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Install .NET
ENV DOTNET_VERSION 5.0.0

RUN wget -O dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_VERSION/dotnet-runtime-$DOTNET_VERSION-linux-musl-x64.tar.gz \
    && dotnet_sha512='c112bdc4308c0b49fa4f4f9845bf13bfcfe2debed9166e6e6922f389c043d6f7f55a7cc3e03778c08df3ffd415059b90dfb87ce84c95a0fb1de0a6e9f4428b6f' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -C /usr/share/dotnet -oxzf dotnet.tar.gz \
    && rm dotnet.tar.gz

COPY ./build/net5.0 /app/build/net5.0
COPY ./configuration /app/configuration

WORKDIR /app/build/net5.0

EXPOSE 1337 5001

ENTRYPOINT ["dotnet", "NosCore.WorldServer.dll"]
