# cf https://github.com/dotnet/dotnet-docker/blob/main/src/aspnet/10.0/alpine3.21/amd64/Dockerfile

ARG REPO=mcr.microsoft.com/dotnet/runtime
FROM $REPO:10.0-alpine3.21-amd64

# .NET globalization APIs will use invariant mode by default because DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true is set
# by the base runtime-deps image. See https://aka.ms/dotnet-globalization-alpine-containers for more information.

# ASP.NET Core version
ENV ASPNET_VERSION=10.0
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Install ASP.NET Core
RUN wget -O aspnetcore.tar.gz https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/$ASPNET_VERSION/aspnetcore-runtime-$ASPNET_VERSION-linux-musl-x64.tar.gz \
    && tar -oxzf aspnetcore.tar.gz -C /usr/share/dotnet ./shared/Microsoft.AspNetCore.App \
    && rm aspnetcore.tar.gz
	
# Update package list and install libicu (ICU libraries) for Alpine
RUN apk update \
    && apk add --no-cache icu-libs
	
COPY ./build/net10.0 /app/build/net10.0
COPY ./configuration /app/configuration

WORKDIR /app/build/net10.0

EXPOSE 4002

ENTRYPOINT ["dotnet", "NosCore.LoginServer.dll"]
