//  __  _  __    __   ___ __  ___ ___  
// |  \| |/__\ /' _/ / _//__\| _ \ __| 
// | | ' | \/ |`._`.| \_| \/ | v / _|  
// |_|\__|\__/ |___/ \__/\__/|_|_\___| 
// 
// Copyright (C) 2019 - NosCore
// 
// NosCore is a free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.ComponentModel.DataAnnotations;
using NosCore.Data.I18N;
using NosCore.Data.Dto;
using NosCore.Data.StaticEntities;
using NosCore.Data.DataAttributes;
using NosCore.Data.Enumerations.I18N;
using Mapster;

namespace NosCore.Data.StaticEntities
{
	/// <summary>
	/// Represents a DTO class for NosCore.Database.Entities.BCard.
	/// NOTE: This class is generated by GenerateDtos.tt
	/// </summary>
	public class BCardDto : IStaticDto
	{
		[Key]
		public short BCardId { get; set; }

	 	public byte SubType { get; set; }

	 	public byte Type { get; set; }

	 	public int FirstData { get; set; }

	 	public int SecondData { get; set; }

	 	internal CardDto Card { get; set; }

	 	internal ItemDto Item { get; set; }

	 	internal SkillDto Skill { get; set; }

	 	internal NpcMonsterDto NpcMonster { get; set; }

	 	public short? CardId { get; set; }

	 	public short? ItemVNum { get; set; }

	 	public short? SkillVNum { get; set; }

	 	public short? NpcMonsterVNum { get; set; }

	 	public byte CastType { get; set; }

	 	public int ThirdData { get; set; }

	 	public bool IsLevelScaled { get; set; }

	 	public bool IsLevelDivided { get; set; }

	 }
}