//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosCore.Shared.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NosCore.Shared.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with SessionId {0} has arrived..
        /// </summary>
        public static string ACCOUNT_ARRIVED {
            get {
                return ResourceManager.GetString("ACCOUNT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurer.
        /// </summary>
        public static string ADVENTURER {
            get {
                return ResourceManager.GetString("ADVENTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken!.
        /// </summary>
        public static string ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        public static string ARCHER {
            get {
                return ResourceManager.GetString("ARCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least on of required files is missing.
        /// </summary>
        public static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Error.
        /// </summary>
        public static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Auth.
        /// </summary>
        public static string AUTH_INCORRECT {
            get {
                return ResourceManager.GetString("AUTH_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated Error..
        /// </summary>
        public static string AUTHENTICATED_ERROR {
            get {
                return ResourceManager.GetString("AUTHENTICATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated Success!.
        /// </summary>
        public static string AUTHENTICATED_SUCCESS {
            get {
                return ResourceManager.GetString("AUTHENTICATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string BAD_PASSWORD {
            get {
                return ResourceManager.GetString("BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cards Parsed!.
        /// </summary>
        public static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Not loaded.
        /// </summary>
        public static string CHARACTER_NOT_INIT {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected, SessionId: {0}.
        /// </summary>
        public static string CLIENT_ARRIVED {
            get {
                return ResourceManager.GetString("CLIENT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client connected. ClientId = {0}.
        /// </summary>
        public static string CLIENT_CONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed..
        /// </summary>
        public static string CLIENT_DISCONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet with Header {0} is corrupt or PacketDefinition is invalid. Content: {1}.
        /// </summary>
        public static string CORRUPT_PACKET {
            get {
                return ResourceManager.GetString("CORRUPT_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Keepalive on client {0}.
        /// </summary>
        public static string CORRUPTED_KEEPALIVE {
            get {
                return ResourceManager.GetString("CORRUPTED_KEEPALIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database has been initialized..
        /// </summary>
        public static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database may not be up to date. Please consider updating your database..
        /// </summary>
        public static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing done!.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the directory of files to parse.
        /// </summary>
        public static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character changed while changing map. Do not abuse Commands. {0}.
        /// </summary>
        public static string ERROR_CHANGE_MAP {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Disconnecting of client {0}, too much connections..
        /// </summary>
        public static string FORCED_DISCONNECTION {
            get {
                return ResourceManager.GetString("FORCED_DISCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler Error.
        /// </summary>
        public static string HANDLER_ERROR {
            get {
                return ResourceManager.GetString("HANDLER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found Handler implementation for Packet with Header {0}.
        /// </summary>
        public static string HANDLER_NOT_FOUND {
            get {
                return ResourceManager.GetString("HANDLER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N ActDescs Parsed! Region: {1}.
        /// </summary>
        public static string I18N_ACTDESC_PARSED {
            get {
                return ResourceManager.GetString("I18N_ACTDESC_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N BCards Parsed! Region: {1}.
        /// </summary>
        public static string I18N_BCARD_PARSED {
            get {
                return ResourceManager.GetString("I18N_BCARD_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Cards Parsed! Region: {1}.
        /// </summary>
        public static string I18N_CARD_PARSED {
            get {
                return ResourceManager.GetString("I18N_CARD_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Items Parsed! Region: {1}.
        /// </summary>
        public static string I18N_ITEM_PARSED {
            get {
                return ResourceManager.GetString("I18N_ITEM_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N MapIdDatas Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MAPIDDATA_PARSED {
            get {
                return ResourceManager.GetString("I18N_MAPIDDATA_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N MapPointDatas Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MAPPOINTDATA_PARSED {
            get {
                return ResourceManager.GetString("I18N_MAPPOINTDATA_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N NpcMonsters Parsed! Region: {1}.
        /// </summary>
        public static string I18N_MPCMONSTER_PARSED {
            get {
                return ResourceManager.GetString("I18N_MPCMONSTER_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N NpcMonsterTalk Parsed! Region: {1}.
        /// </summary>
        public static string I18N_NPCMONSTERTALK_PARSED {
            get {
                return ResourceManager.GetString("I18N_NPCMONSTERTALK_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Quests Parsed! Region: {1}.
        /// </summary>
        public static string I18N_QUEST_PARSED {
            get {
                return ResourceManager.GetString("I18N_QUEST_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I18N Skills Parsed! Region: {1}.
        /// </summary>
        public static string I18N_SKILL_PARSED {
            get {
                return ResourceManager.GetString("I18N_SKILL_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Id!.
        /// </summary>
        public static string INVALID_ACCOUNT {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in your nickname!.
        /// </summary>
        public static string INVALID_CHARNAME {
            get {
                return ResourceManager.GetString("INVALID_CHARNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password!.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items parsed!.
        /// </summary>
        public static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Port {0}.
        /// </summary>
        public static string LISTENING_PORT {
            get {
                return ResourceManager.GetString("LISTENING_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magician.
        /// </summary>
        public static string MAGICIAN {
            get {
                return ResourceManager.GetString("MAGICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MapMonsters Loaded!.
        /// </summary>
        public static string MAPMONSTERS_LOADED {
            get {
                return ResourceManager.GetString("MAPMONSTERS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Maps Loaded!.
        /// </summary>
        public static string MAPS_LOADED {
            get {
                return ResourceManager.GetString("MAPS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Map Parsed!.
        /// </summary>
        public static string MAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterServer started successfully..
        /// </summary>
        public static string MASTER_SERVER_LISTENING {
            get {
                return ResourceManager.GetString("MASTER_SERVER_LISTENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Master Server! Trying again in 5 seconds....
        /// </summary>
        public static string MASTER_SERVER_RETRY {
            get {
                return ResourceManager.GetString("MASTER_SERVER_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server need at least nosville MAP to work!.
        /// </summary>
        public static string NO_MAP {
            get {
                return ResourceManager.GetString("NO_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Accounts?.
        /// </summary>
        public static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse ALL?.
        /// </summary>
        public static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Cards?.
        /// </summary>
        public static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse I18N datas?.
        /// </summary>
        public static string PARSE_I18N {
            get {
                return ResourceManager.GetString("PARSE_I18N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Items?.
        /// </summary>
        public static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse MapNpcs?.
        /// </summary>
        public static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Maps?.
        /// </summary>
        public static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse MapTypes? we suggest using with MapTypeMaps.
        /// </summary>
        public static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse NpcMonsters?.
        /// </summary>
        public static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse NpcMonsterData?.
        /// </summary>
        public static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Npcs?.
        /// </summary>
        public static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Portals?.
        /// </summary>
        public static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Quests?.
        /// </summary>
        public static string PARSE_QUESTS {
            get {
                return ResourceManager.GetString("PARSE_QUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Recipes?.
        /// </summary>
        public static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shopitems?.
        /// </summary>
        public static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shops?.
        /// </summary>
        public static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Shopskills?.
        /// </summary>
        public static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Skills?.
        /// </summary>
        public static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse Teleporters?.
        /// </summary>
        public static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to parse TimeSpaces?.
        /// </summary>
        public static string PARSE_TIMESPACES {
            get {
                return ResourceManager.GetString("PARSE_TIMESPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Portal Parsed!.
        /// </summary>
        public static string PORTALS_PARSED {
            get {
                return ResourceManager.GetString("PORTALS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered on MasterServer.
        /// </summary>
        public static string REGISTRED_FROM_MASTER {
            get {
                return ResourceManager.GetString("REGISTRED_FROM_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered on MasterServer.
        /// </summary>
        public static string REGISTRED_ON_MASTER {
            get {
                return ResourceManager.GetString("REGISTRED_ON_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Select a MapId:.
        /// </summary>
        public static string SELECT_MAPID {
            get {
                return ResourceManager.GetString("SELECT_MAPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Loaded!.
        /// </summary>
        public static string SUCCESSFULLY_LOADED {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter {0}.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swordman.
        /// </summary>
        public static string SWORDMAN {
            get {
                return ResourceManager.GetString("SWORDMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Master Packet..
        /// </summary>
        public static string UNRECOGNIZED_MASTER_PACKET {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_MASTER_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistred From Master..
        /// </summary>
        public static string UNREGISTRED_FROM_MASTER {
            get {
                return ResourceManager.GetString("UNREGISTRED_FROM_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrestler.
        /// </summary>
        public static string WRESTLER {
            get {
                return ResourceManager.GetString("WRESTLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong MapId!.
        /// </summary>
        public static string WRONG_SELECTED_MAPID {
            get {
                return ResourceManager.GetString("WRONG_SELECTED_MAPID", resourceCulture);
            }
        }
    }
}
