<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TieredCompilation>true</TieredCompilation>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <NosCoreGeneratePacketHandlerLists>true</NosCoreGeneratePacketHandlerLists>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="NosCoreGeneratePacketHandlerLists" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NosCore.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NosCore.GameObject\NosCore.GameObject.csproj" />
    <ProjectReference Include="..\..\tools\NosCore.DiGenerator\NosCore.DiGenerator.csproj"
        OutputItemType="Analyzer"
        ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
