//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosCore.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NosCore.Core.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Account with SessionId {0} has arrived..
        /// </summary>
        public static string ACCOUNT_ARRIVED {
            get {
                return ResourceManager.GetString("ACCOUNT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a At least on of required files is missing.
        /// </summary>
        public static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Authenticated Error..
        /// </summary>
        public static string AUTHENTICATED_ERROR {
            get {
                return ResourceManager.GetString("AUTHENTICATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Authenticated Success!.
        /// </summary>
        public static string AUTHENTICATED_SUCCESS {
            get {
                return ResourceManager.GetString("AUTHENTICATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} cards parsed!.
        /// </summary>
        public static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Character Not loaded.
        /// </summary>
        public static string CHARACTER_NOT_INIT {
            get {
                return ResourceManager.GetString("CHARACTER_NOT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connection closed..
        /// </summary>
        public static string CLIENT_DISCONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database has been initialized..
        /// </summary>
        public static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database may not be up to date. Please consider updating your database..
        /// </summary>
        public static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parsing done!.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please enter the directory of files to parse.
        /// </summary>
        public static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong Id!.
        /// </summary>
        public static string INVALID_ACCOUNT {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong Password!.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} items parsed!.
        /// </summary>
        public static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Accounts?.
        /// </summary>
        public static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse ALL?.
        /// </summary>
        public static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Cards?.
        /// </summary>
        public static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Items?.
        /// </summary>
        public static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse MapNpcs?.
        /// </summary>
        public static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Maps?.
        /// </summary>
        public static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse MapTypes? we suggest using with MapTypeMaps.
        /// </summary>
        public static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse NpcMonsters?.
        /// </summary>
        public static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse NpcMonsterData?.
        /// </summary>
        public static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Npcs?.
        /// </summary>
        public static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Portals?.
        /// </summary>
        public static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Quests?.
        /// </summary>
        public static string PARSE_QUESTS {
            get {
                return ResourceManager.GetString("PARSE_QUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Recipes?.
        /// </summary>
        public static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Shopitems?.
        /// </summary>
        public static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Shops?.
        /// </summary>
        public static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Shopskills?.
        /// </summary>
        public static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Skills?.
        /// </summary>
        public static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse Teleporters?.
        /// </summary>
        public static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to parse TimeSpaces?.
        /// </summary>
        public static string PARSE_TIMESPACES {
            get {
                return ResourceManager.GetString("PARSE_TIMESPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registered on MasterServer.
        /// </summary>
        public static string REGISTRED_ON_MASTER {
            get {
                return ResourceManager.GetString("REGISTRED_ON_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Successfully Loaded!.
        /// </summary>
        public static string SUCCESSFULLY_LOADED {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unrecognized Master Packet..
        /// </summary>
        public static string UNRECOGNIZED_MASTER_PACKET {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_MASTER_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unregistred From Master..
        /// </summary>
        public static string UNREGISTRED_FROM_MASTER {
            get {
                return ResourceManager.GetString("UNREGISTRED_FROM_MASTER", resourceCulture);
            }
        }
    }
}
